### ISSUE TITLE
No special exception handling for proxy or time outs

### ISSUE THREAD

**Issue by SurenderHarsha** [shubhamc183/AmazonSearch#3]
If you are behind a proxy server, or your internet is slow or the website is blocked due to some reason.
Official support for such issues is not provided and You have to google them out or solve them on your own.
This package is only for the purpose of providing you a basic idea on how to scrape.

**Comment by shubhamc183** [comment]
If you are behind proxy server 
For Windows
Run any of these:-
set http_proxy=http://your_proxy:your_port
set http_proxy=http://username:password@your_proxy:your_port
set https_proxy=https://your_proxy:your_port

For linux,,,see
http://www.cyberciti.biz/faq/linux-unix-set-proxy-environment-variable/
set https_proxy=https://username:password@your_proxy:your_port
